---
- name: Configure custom services
  blockinfile:
    block: "{{ icinga2_custom_plugin_commands }}"
    path: "{{ icinga2_shared_path }}/include/command-plugins.conf"
    state: present
  notify: reload icinga
  tags:
    - configure
    - configure_commands
...
